import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

const LAST_UPDATED = "July 21, 2026";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 px-4 py-16 sm:px-6">
      <div className="space-y-2">
        <h1 className="text-2xl font-semibold">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated {LAST_UPDATED}</p>
      </div>

      <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
        <p>By creating an account or using Summit, you agree to these terms.</p>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">Not financial advice</h2>
          <p>
            Summit is an educational tool. Every score, recommendation, projection, and answer from the AI Financial
            Coach is generated by rule-based logic applied to the numbers you enter — it is not personalized
            investment, tax, legal, or financial advice, and it does not constitute a recommendation to buy, sell,
            or hold any security. Summit is not a registered investment adviser, broker-dealer, or bank. Projections
            rely on simplifying assumptions (e.g. an assumed average investment return) that are disclosed where
            used, and real-world results will differ. Always use your own judgment, and consult a licensed
            professional before making significant financial decisions.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">Your account</h2>
          <p>
            You&apos;re responsible for keeping your login credentials secure and for the accuracy of the financial
            information you enter — Summit&apos;s calculations are only as good as the numbers you provide.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">Acceptable use</h2>
          <p>
            Don&apos;t use Summit to violate any law, attempt to access another user&apos;s data, or disrupt the
            service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">&quot;As is&quot; service</h2>
          <p>
            Summit is provided &quot;as is,&quot; without warranty of any kind. As an independently operated project, we don&apos;t
            guarantee uninterrupted availability or that any calculation, projection, or recommendation is error-free.
            To the fullest extent permitted by law, Summit and its operator aren&apos;t liable for any decision you
            make based on information from the app.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">Changes</h2>
          <p>
            We may update these terms or the service itself over time. Material changes will update the date at the
            top of this page.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-medium text-foreground">Contact</h2>
          <p>
            Questions about these terms? Email{" "}
            <a href="mailto:jackjudice1@gmail.com" className="underline underline-offset-4">
              jackjudice1@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
