import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  // TODO: swap for a real custom domain once one is connected (see DEPLOYMENT.md).
  metadataBase: new URL("https://personal-finance-engine-sable.vercel.app"),
  title: {
    default: "Summit — Your Next Best Financial Move",
    template: "%s | Summit",
  },
  description:
    "Stop guessing with your finances. Get personalized recommendations to save smarter, invest better, and build wealth faster.",
  openGraph: {
    title: "Summit",
    description: "Your money. Your goals. Your next best decision.",
    url: "https://personal-finance-engine-sable.vercel.app",
    siteName: "Summit",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Summit",
    description: "Your money. Your goals. Your next best decision.",
  },
  // Favicon and Open Graph image are generated by app/icon.tsx and
  // app/opengraph-image.tsx (Next.js metadata file conventions) - no need
  // to reference static files here.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <TooltipProvider delay={200}>
            {children}
            <Toaster richColors position="top-right" />
          </TooltipProvider>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
